POST http://localhost:3000/tasks/create HTTP/1.1
content-type: application/json

{
    "title": "segunda tarea",
    "descripcion": "tarea de prueba para ver la base de datos",
    "fecha": "2022-10-01"
}